platform: linux/arm

pipeline:
  clone:
    image: armswarmdrone/git

  build:
    image: sandlayth/arm-nginx-php-fpm
    commands:
      - find ./app -name "*.php" -print0 | xargs -0 -n1 -P8 php -l > /dev/null
      - echo "[✓] No PHP syntax errors detected in the [ app/ ] folder" > /dev/null
      - composer -q install
      - ./vendor/bin/php-linter ./app/
      - php vendor/bin/security-checker security:check ./ -n
      - cp .env.drone .env
      - php artisan migrate --env=testing --no-interaction -vvv
      - php artisan db:seed --env=testing --no-interaction -vvv
      - ./vendor/bin/phpunit  -vvv
      - php artisan serve > /dev/null 2>&1 &
      - sleep 5
      - curl localhost:8000
      - ./debug_wait_for_webserver.sh
      # - ./vendor/bin/wait-for-webserver
      - curl localhost:8000
      - php -v

  build-node:
    image: hypriot/rpi-node
    commands:
      - yarn install

  ###
  # DEPLOYMENT STEP - fill in the details when set up
  ###
  # deploy:
  #   image: tbd:latest

services:
  database:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

