platform: linux/arm

pipeline:
  restore-composer-cache:
    image: foo/drone-volume-cache
    restore: true
    mount:
      - ~/.composer
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/drone-volume-cache/composer:/cache

  clone:
    image: armswarmdrone/git

  build:
    image: sandlayth/arm-nginx-php-fpm
    commands:
      - ls -la ~/.composer/
      - find ./app -name "*.php" -print0 | xargs -0 -n1 -P8 php -l > /dev/null
      - echo "[✓] No PHP syntax errors detected in the [ app/ ] folder" > /dev/null
      - composer -q install
      - ./vendor/bin/php-linter ./app/
      - php vendor/bin/security-checker security:check ./ -n
      - cp .env.drone .env
      - php artisan migrate --env=testing --no-interaction -vvv
      - php artisan db:seed --env=testing --no-interaction -vvv
      - ./vendor/bin/phpunit  -vvv
      - php artisan serve > /dev/null 2>&1 &
      - ./vendor/bin/wait-for-webserver
      - curl localhost:8000
      - php -v
      - ls -la ~/.composer/

  rebuild-composer-cache:
    image: foo/drone-volume-cache
    rebuild: true
    mount:
      - ~/.composer
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/drone-volume-cache/composer:/cache

  build-node:
    image: hypriot/rpi-node
    commands:
      # TODO: Yarn is not installed. Maybe fork rpi-node and install yarn on it?
      # - yarn install
      - node -v
      - ls -la ~/.composer/

  ###
  # DEPLOYMENT STEP - fill in the details when set up
  ###
  # deploy:
  #   image: tbd:latest

services:
  database:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes


